![Banner](img/banner.png)

# **Actividad N°2:** Matrices positivas definidas

***Matemáticas para Machine Learning.***

Semana 2 - Lección 2: Matrices positivas definidas

**Profesor:** *Fernando Enrique Lozano Martinez* - **Autor Notebook:** *Nicolas Orlando López Cuéllar*

# Introducción

## Descripción

El presente *jupyter notebook* contiene todo el material para el desarrollo de la Tarea 2 de la Semana 2 del curso ***Matemáticas para Machine Learning***. En este se realizarán ejercicios relacionados con matrices positivas definidas, como por ejemplo matrices de correlación y de covarianza.

**Objetivos de Aprendizaje:**

*   Identificar cuando una matriz es positiva definida
*   Identificar matrices positvas en matrices de correlación

## Metodologia

En este taller se implementarán algunos métodos para identificar cuando una matriz es positiva definida. Para esto primero se desarrollará una función que permita obtener una matriz simétrica $A_s$ a partir de otra matriz $A$ de tal manera que las formas cuadráticas de ambas matrices son iguales para todo valor de $\mathbf{x}$. Luego se implementarán 3 métodos para determinar si una matriz es positiva definida y finalmente se implementarán estos métodos sobre un grupo de matrices de correlación.

__________________________________________________________________________________

Para desarrollar el taller usted deberá editar las celdas de código dispuestas para esto. Estas estarán marcadas con el siguiente comentario:

```python
# =====================================================
# COMPLETAR ===========================================
# 

# =====================================================
```

Edite o complete el códgio dentro de estas lineas de comentarios. Dentro de estos comentarios encontrará indicaciónes de lo que debe hacer, así como algunas de las variables que debe utilizar o calcular (puede que estas tengan ya una estructura para llenar o no, revise y complete la asignación). 

En este notebook, cada punto tendrá una sección para probar libremente el trabajo realizado explorando sus resultados, asi como también una sección de pruebas avanzadas las cuales serán autocalificadas. Las secciones de código utilizadas para señalar estos espacios son respectivamente


```python
# PROBAR ==========================================================
funcion_trabajada()
```
y 

```python
### ==========================================================================
### PRUEBAS AVANZADAS ========================================================
pruebas_avanzadas(funcion_trabajada)
```

# Teoria

Una matriz es $A$ se llama **positiva definida** si

$$ \mathbf{x}^T A \mathbf{x} > 0 \quad ∀ \mathbf{x} \neq 0 $$

Se llama **positiva semi-definida** si:

$$ \mathbf{x}^T A \mathbf{x} \geq 0 \quad ∀ \mathbf{x} \neq 0 $$

Note que esta condición implica que $A$ es una matriz cuadrada y si $\mathbf{x} \in \mathbb{R}^n$ entonces $A \in \mathbb{R}^{n \times n}$. También notamos que esta propiedad, al referirse a formas cuadráticas, implica que solo será de particular importancia en matrices simétricas, despues de todo si tenemos una matriz $A$ no simétrica, podemos demostrar que su forma cuadrática es quivalente a la de la matriz simétrica $\frac{1}{2} (A + A^T)$.

## Demostración

---
**Demostración Ilustrativa**

Primero vemos el caso de $A \in \mathbb{R}^2$: $ A = \begin{bmatrix} a & b \\ c& d \end{bmatrix}$

Matriz original:

$$\begin{split} \mathbf{x}^T A \mathbf{x} &
=
\begin{bmatrix} x_1 & x_2 \end{bmatrix}  \begin{bmatrix} a & b \\ c & d \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}
=
\begin{bmatrix} x_1 & x_2 \end{bmatrix}  \begin{bmatrix} ax_1 +  bx_2 \\ cx_1 + d x_2 \end{bmatrix}
= 
x_1 ( ax_1 + bx_2 ) + x_2 (cx_1 + dx_2) \\ \\
& = a x_1^2 + (b + c)(x_1x_2) + d x_2^2
\end{split} $$


Matriz simétrica:

$$\begin{split} \mathbf{x}^T \frac{1}{2}(A + A^T) \mathbf{x} &
=
\begin{bmatrix} x_1 & x_2 \end{bmatrix}  \begin{bmatrix} \frac{a+a}{2} & \frac{b+c}{2} \\ \frac{c+b}{2} & \frac{d + d}{2} \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}
=
\begin{bmatrix} x_1 & x_2 \end{bmatrix}  \begin{bmatrix} a x_1 +  \frac{c+b}{2} x_2 \\ \frac{c+b}{2} x_1 + d x_2 \end{bmatrix}
= 
x_1 \left( ax_1 + \frac{c+b}{2} x_2 \right) + x_2 \left( \frac{c+b}{2} x_1 + dx_2 \right) \\ \\
& = a x_1^2 + (b + c)(x_1x_2) + d x_2^2
\end{split} $$

---


---
**Demostración General**

Primero vemos el caso de $A \in \mathbb{R}^{n\times n}$: $ A = \begin{bmatrix} a_{11} & \dots & a_{1n} \\ \vdots & \ddots & \vdots \\ a_{n1} & \dots & a_{nn} \end{bmatrix}$

$$\begin{split} \mathbf{x}^T A \mathbf{x} &
=
\begin{bmatrix} x_1 & \dots & x_n \end{bmatrix}  \begin{bmatrix} a_{11} & \dots & a_{1n} \\ \vdots & \ddots & \vdots \\ a_{n1} & \dots & a_{nn} \end{bmatrix} \begin{bmatrix} x_1 \\ \dots \\ x_2 \end{bmatrix}
=
\begin{bmatrix} x_1  & \dots & x_n \end{bmatrix}  \begin{bmatrix} a_{11}x_1 + \ldots + a_{1n}x_n \\ \vdots \\ a_{n1}x_1 + \ldots + a_{nn} x_n \end{bmatrix} \\ \\
& = 
x_1 ( a_{11}x_1 + \ldots + a_{1n}x_n  ) + x_2 (a_{21}x_1 + \ldots + a_{2n}x_n ) + \ldots + x_n(a_{n1}x_1 + \ldots + a_{nn}x_n ) \\ \\
& = \sum_{i} a_{ii}x_i^2 + \sum_{j \neq i} (a_{ji} + a_{ij}) x_i x_j \\ \\
\end{split} $$


$$\begin{split} \mathbf{x}^T \frac{1}{2}(A + A^T) \mathbf{x} &
=
\begin{bmatrix} x_1 & \dots & x_n \end{bmatrix} \frac{1}{2} \begin{bmatrix} a_{11}+a_{11} & a_{12} + a_{21} & \dots & a_{1n} + a_{n1} \\ a_{21}+a_{12} & a_{22} + a_{22} & \dots & a_{2n} + a_{n2} \\ \vdots & \vdots & \dots & \dots \\
a_{n1}+a_{1n} & a_{n2} + a_{2n} & \dots & a_{nn} + a_{nn} \end{bmatrix} \begin{bmatrix} x_1 \\ \vdots \\ x_n \end{bmatrix} \\ \\
& =
\begin{bmatrix} 
x_1 & \dots & x_n  \end{bmatrix}  \begin{bmatrix} a_{11} x_1 +  \frac{a_{12}+a_{21}}{2} x_2 + \ldots + \frac{a_{1n}+a_{n1}}{2} x_n \\
 \frac{a_{12}+a_{21}}{2} x_1 +  a_{22} x_2 + \ldots + \frac{a_{2n}+a_{n2}}{2} x_n \\
\vdots \\
\frac{a_{1n}+a_{n1}}{2} x_1 +  \frac{a_{n2}+a_{2n}}{2} x_2 + \ldots + a_{nn} x_n \end{bmatrix} \\ \\
& =\sum_{i} a_{ii}x_i^2 + \sum_{j \neq i} (a_{ji} + a_{ij}) x_i x_j \\ \\
\end{split} $$


---

## Condiciones para ser p.d.

Sin embargo, esta condición es imposible de verificar en la vida real, por lo que existen otras equivalencias que permiten identificar cuando una matriz es positiva definida:


1.   Todos los valores propios $\lambda_i > 0$  
2.   Todos los deterinantes superiores izquierdos son positivos

$$ \textrm{ Ejemplo } $$
$$ A =  \begin{bmatrix}
 a_{11} & a_{12} & a_{13} & a_{14} \\
 a_{21} & a_{22} & a_{23} & a_{24} \\
 a_{31} & a_{32} & a_{33} & a_{34} \\
 a_{41} & a_{42} & a_{43} & a_{44} \\
\end{bmatrix}$$

$$
\left| \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
 a_{21} & a_{22} & a_{23} \\
 a_{31} & a_{32} & a_{33} 
\end{bmatrix} \right|> 0 
\qquad
\left| \begin{bmatrix}
a_{11} & a_{12} \\
 a_{21} & a_{22} 
\end{bmatrix} \right|> 0 
\qquad
\big| \begin{bmatrix}
a_{11} 
\end{bmatrix} \big|> 0 
\qquad ⟹ \qquad 
A \textrm{ es postiva definida}
$$

3.   Cuando la matriz se lleva a forma escalonada, todos los pivotes son positivos

$$ A =  \begin{bmatrix}
 a_{11} & a_{12} & a_{13} & a_{14} \\
 a_{21} & a_{22} & a_{23} & a_{24} \\
 a_{31} & a_{32} & a_{33} & a_{34} \\
 a_{41} & a_{42} & a_{43} & a_{44} \\
\end{bmatrix} ⟶ A^* = \begin{bmatrix}
 a_{1} & a_{5} & a_{8} & a_{10} \\
 0 & a_{2} & a_{6} & a_{9} \\
 0 & 0 & a_{3} & a_{7} \\
 0 & 0 & 0 & a_{4} \\
\end{bmatrix} \\
$$ 


Entonces si $ a_1 > 0 , a_2 > 0 , a_3 > 0$  y $ a_4 > 0$ entonces decimos que la matriz es positiva definida.



# Problemas

A continuación se presentan una serie de problemas que nos permitirán evaluar distintos métodos de identificar matrices positivas definidas. Primero, importamos las librerias necesarias para el laboratorio.

In [1]:
# Librerias Básicas
import numpy as np      
import pandas as pd
from sklearn import datasets

# Visualización
from IPython.display import display, HTML
from tqdm.notebook import tqdm
import warnings
warnings.filterwarnings("ignore")

In [2]:
# UTILIDADES =================================
# Correr una única vez por sesión ============
from maiautils import MaiaUtils
ipython = get_ipython()
mutils = MaiaUtils(ipython) 
# ============================================

In [3]:
# Cambiar configuración de informe de errores
mutils.toggle_traceback()

## Matrices de trabajo

Considere la siguiente matriz: 
$$ A = \begin{bmatrix} 
1 & -1 & 2 & 0 \\
-1 & 4 & -1 & 1 \\
2 & -1 & 6 & 2 \\
0 & -1 & 2 & 4 
\end{bmatrix} $$

Como se puede observar, esta matriz no es simétrica. Complete la siguiente función para obtener la forma simétrica de una matriz

In [4]:
# Matriz base
A =[[1, -1, 2, 0],
    [-1, 4,-1, 1],
    [2, -1, 6, 2],
    [0, -1, 2, 4]]

In [5]:
A = np.array(A)

In [6]:
def obtener_forma_simetrica(A):
    """ 
    Obtiene la matriz simétrica cuya forma cuadrática es igual a la de A
    ___________________________________
    Entrada:
    A:   [2D-array] Matriz a transformar
    ___________________________________
    Salida:
    Aout: [2D-array] Forma simétrica de la matriz
    """
    # =====================================================
    # COMPLETAR ===========================================
    if A.shape[0]!= A.shape[1]:
        raise ValueError("La matriz debe ser cuadrada.")
       
    # Crear una matriz vacía del mismo tamaño que la matriz dada.
    #Aout = np.zeros_like(A)
    Aout =1/2*(A +np.transpose(A))
    # AYUDA:
    # Estructura de Salida
    #Aout = np.identity(len(A))
    # =====================================================

    return Aout

In [7]:
obtener_forma_simetrica(A)

array([[ 1., -1.,  2.,  0.],
       [-1.,  4., -1.,  0.],
       [ 2., -1.,  6.,  2.],
       [ 0.,  0.,  2.,  4.]])

### Verificar forma simétrica

Podemos verificar que la teoria presentada anteriormente es correcta revisando varias evaluaciones de las fomras cuadráticas de la matriz original y la matriz simétrica obtenida. Tamnbién es importante verificar que la matriz obtenida es una matriz simétrica.

In [8]:
def verificar_forma_cuadratica(A, As, ntest=1000):
    """
    Verifica que las formas cuadráticas x^TAx y x^TAsx sean iguales
    para varios valores de x. Interrumpe ejecución en caso de errores
    ___________________________________
    Entrada:
    A: [2D-array] Matriz a verificar
    As: [2D-array] Matriz a en forma simétrica
    ntest: [int] número de iteraciones a probar
    """
    # Datos aleatorios para probar
    X = np.random.rand(ntest, np.array(A).shape[0])
    
    # Calculo forma cuadrática y compara
    for x in X:
        assert round(x@A@x, 3) == round(x@As@x, 3), f'ERROR en forma cuadrática: \n\nx = {x}\n\nResultado A : {x@A@x}\nResultad0 As: {x@As@x}'
    print(f"No se encontraron errores en {ntest} pruebas")
    
    
def verificar_forma_simetrica(As):
    """ 
    Verifica que la la matriz sea simétrica
    ___________________________________
    Entrada:
    A: [2D-array] Matriz a verificar
    """
    # Verifica que la matriz sea simétrica
    if (As != As.T).any():
        print("La matriz obtenida no es simètrica:")
        print(f'As=\n{As} \n\nAs^T=\n{As.T}')
        assert False
    print("La matriz obtenida es simétrica")

In [9]:
# Obtiene matriz a partir de la función creada
As = np.array(obtener_forma_simetrica(A))

In [10]:
As

array([[ 1., -1.,  2.,  0.],
       [-1.,  4., -1.,  0.],
       [ 2., -1.,  6.,  2.],
       [ 0.,  0.,  2.,  4.]])

In [11]:
# Verifica forma cuadrática
verificar_forma_cuadratica(A, As, ntest=1000)

No se encontraron errores en 1000 pruebas


In [12]:
# Verifica que la matriz sea simétrica
verificar_forma_simetrica(As)

La matriz obtenida es simétrica


### Funciones adicionales

Para probar los siguientes métodos utilizamos una función que para cada dimensión $d$ en la lista dim produce $2n$ matrices de dimensiones $d\times d$, donde al menos $n$ de estas matrices son positivas definidas. También usamos una segunda función que nos permite observar los resultados de aplicar nuestra función de identificación de matrices p.d.sobre un grupo de matrices.

In [13]:
help(mutils.generar_matrices_balanceadas)

Help on function generar_matrices_balanceadas in module datos:

generar_matrices_balanceadas(dim=[2, 3], n=2, rnd=1, as_int=True)
    Genera matrices positivas definidas y aleatorias
    ___________________________________
    Entrada:
    dim: [1D-array] lista de dimensiones
    n: [int] matrices pd y aleatorias por dimensión
    rnd: [int] semilla de aleatoriedad
    as_int: [bool] llevar los números a enteros
    ___________________________________
    Salida:
    A_list: [list]  Lista de matrices



In [14]:
help(mutils.mostrar_resultados)

Help on method mostrar_resultados in module maiautils:

mostrar_resultados(Alist, test_fun, matrices=True, valores=True) method of maiautils.MaiaUtils instance
    Prueba la función test_fun para verificar cada matriz A en Alist por la
    propiedad de ser positiva definida
    ___________________________________
    Entrada:
    Alist:    [1D-array] Lista de matrices
    test_fun: [function] función que identifica si una matriz es p.d.
    matrices: [bool] Muestra matrices usadas
    calores:  [bool] Muestra valores de prueba encontrados
    ___________________________________
    Salida:
    Muestra resultados en consola



## Test valores propios

En el test de valores propios hay que verificar que todos los valores propios de la matriz sean mayores o iguales que 0

### Ejemplo básico

Demuestre que la forma simétrica de $A$ es positiva definida a partir del método de vectores propios. Encuentre los valores propios de A y verifique que todos sean mayores que 0.

In [15]:
# =====================================================
# COMPLETAR ===========================================
# -
# AYUDA:
# Estructura esperada
A_sim = obtener_forma_simetrica(A)
vprop =np.linalg.eigvals(A_sim)
# =====================================================

In [16]:
vprop

array([8.        , 0.08777082, 4.19869124, 2.71353793])

In [17]:
vprop_round = [round(it, 3) for it in vprop]
vprop_round

[8.0, 0.088, 4.199, 2.714]

In [18]:
# Identifica si es positiva definida
if vprop[0] > 0 and vprop[1] > 0 and vprop[2] > 0 and vprop[3] > 0:
    print('Todos los valores propioes son mayores que 0 i.e la matriz es positiva definida')
else: 
    print('Error, la matrix no se identifica como positiva definida')

Todos los valores propioes son mayores que 0 i.e la matriz es positiva definida


In [19]:
# =====================================================
# VERIFICACIÓN ========================================

# Valores reales
true_vprop = [8., 0.088,  4.199,  2.714]

# Redondea valores obtenidos
vprop_round = [round(it, 3) for it in vprop]

# Verifica valores propios
for val in true_vprop:
    assert val in vprop_round, f'EL valor propio {val} no fue identificado correctamente'

### Método general

Utilice métodos de python para realizar una función que determine si una matriz es positiva definida. Encuentre los valores propios y a partir de eso tome su decisión.

In [20]:
def positiva_definida_vprop(A):
    """ 
    Verifica si una matriz es positva definida
    utiliza el método de valores propioes
    ___________________________________
    Entrada:
    A:   [2D-array] Matriz a revisar
    ___________________________________
    Salida:
    w : [1D-array] lista de valores propios 
    out: [boolean]  Respuesta de verificación. True: Es p.d. False: no es p.d.
    """

    # =====================================================
    # COMPLETAR ===========================================
    # -
    # AYUDA:
    # Estructura de Salida
    A_sim = obtener_forma_simetrica(A)
    w =  np.linalg.eigvals(A_sim)
    for val in w:
        if val < 0:
            out = False
            break 
        else:
            out = True
            pass 

    # =====================================================

    return out, w 

### Prueba

In [21]:
# PROBAR =====================================================

Alist = mutils.generar_matrices_balanceadas(dim=[5,2,3], n=10, rnd=1, as_int=True)

mutils.mostrar_resultados(Alist, positiva_definida_vprop)


792	-525	-27
-525	312	-89
-27	-89	573

La matriz NO ES positiva definida
Los valores obtenidos para esta prueba son:
-38.363
1130.427
584.936
__________________________________

690	706	-112
706	-242	555
-112	555	-411

La matriz NO ES positiva definida
Los valores obtenidos para esta prueba son:
1090.246
-1073.567
20.322
__________________________________

3023	1049	299
1049	1164	280
299	280	334

La matriz ES positiva definida
Los valores obtenidos para esta prueba son:
3541.974
730.924
248.102
__________________________________

30	-466	-942	-732	332
-466	-194	258	-409	325
-942	258	-72	-306	301
-732	-409	-306	267	264
332	325	301	264	543

La matriz NO ES positiva definida
Los valores obtenidos para esta prueba son:
-1577.765
-443.997
1190.155
761.916
643.691
__________________________________

746	379	-139
379	-901	586
-139	586	-432

La matriz NO ES positiva definida
Los valores obtenidos para esta prueba son:
-1370.443
829.13
-45.687
__________________________________

482	-343
-343	

In [22]:
# ============================================================
# PRUEBAS AVANZADAS ==========================================
# ============================================================

mutils.correr_prueba_positiva_definida_vprop(positiva_definida_vprop)


__________________________________
Verificando errores...




Sin Errores
__________________________________


## Test Determinantes submatrices principales

En el test de de determinantes de submatrices principales hay que verificar que todos los determinantes superiores izquierdos de la matriz sean mayores que 0.

### Ejemplo Basico

Demuestre que $A$ es positiva definida a partir del método de determinantes de submatrices principales. Encuentre los valores de determinate para todas las submatrices principales superiores de $A$.



In [23]:
# =====================================================
# COMPLETAR ===========================================
# -
# AYUDA:
# Estructura esperada
det = []
A_sim = obtener_forma_simetrica(A) 
n, m = A_sim.shape
for i in range(n):
    A_Sub = A_sim[:i + 1  , : i+ 1]
    det_Asub = round(np.linalg.det(A_Sub),2) 
    det.append(det_Asub)
# =====================================================

# Identifica si es positiva definida
if det[0] > 0 and det[1] > 0 and det[2] > 0 and det[3] > 0:
    print('Todos los determinantes principales son mayores que 0 i.e la matriz es positiva definida')
else: 
    print('Error, la matrix no se identifica como positiva definida')

Todos los determinantes principales son mayores que 0 i.e la matriz es positiva definida


In [24]:
 # VERIFICACIÓN ==============================

# Valores reales
true_det = [1, 3, 5, 8]
# Redondea valores
det_round = [round(it, 2) for it in det]

# Verifica valores de determinantes
for i, val in enumerate(true_det):
  assert val in det_round, f'El determinante izquierdo #{i+1} con valor {val} no fue identificado correctamente'

### Método General

Utilice la libreria numpy para realizar una función que determine si una matriz es positiva definida . Encuentre el valor de los determinantes principales y a partir de eso tome su decisión.

In [26]:
def positiva_definida_det(A):
    """ 
    Verifica si una matriz es positva definida
    utiliza el método de determinantes
    ___________________________________
    Entrada:
     A:   [2D-array] Matriz a revisar
    ___________________________________
    Salida:
    dets : [1D-array] lista de valores determinantes de submatrices principales 
    out: [boolean]  Respuesta de verificación. True: Es p.d. False: no es p.d.
    """
    # =====================================================
    # COMPLETAR ===========================================
    # -
    # AYUDA:
    # Estructura esperada
    dets = []
    n,m  = A.shape
    for i in range(n):
        A_Sub = A[:i + 1  , : i+ 1]
        det_Asub = round(np.linalg.det(A_Sub),3) 
        dets.append(det_Asub)
        
    for x in dets:
        if x < 0:
            out = False
            break 
        else:
            out = True 

    # =====================================================
  
    return out, dets

### Prueba

In [27]:
Alist = mutils.generar_matrices_balanceadas(dim=[2,3], n=2, rnd=1, as_int=True)

mutils.mostrar_resultados(Alist, positiva_definida_det)


-406	-74	-39
-74	-117	-568
-39	-568	-172

La matriz NO ES positiva definida
Los valores obtenidos para esta prueba son:
-406.0
42026.0
120656333.0
__________________________________

2255	-478
-478	496

La matriz ES positiva definida
Los valores obtenidos para esta prueba son:
2255.0
889996.0
__________________________________

-408	229	-167
229	-468	-388
-167	-388	-712

La matriz NO ES positiva definida
Los valores obtenidos para esta prueba son:
-408.0
138503.0
5536436.0
__________________________________

791	677	-39
677	3320	11
-39	11	300

La matriz ES positiva definida
Los valores obtenidos para esta prueba son:
791.0
2167791.0
644611003.0
__________________________________

1913	610
610	326

La matriz ES positiva definida
Los valores obtenidos para esta prueba son:
1913.0
251538.0
__________________________________

3214	528	133
528	536	87
133	87	177

La matriz ES positiva definida
Los valores obtenidos para esta prueba son:
3214.0
1443920.0
233984746.0
_________________________

In [28]:
# ============================================================
# PRUEBAS AVANZADAS ==========================================
# ============================================================

mutils.correr_prueba_positiva_definida_det(positiva_definida_det)


__________________________________
Verificando errores...




Sin Errores
__________________________________


## Test pivotes

En el test de los pivotes hay que verificar que cuando una matriz es reducida en su forma escalonada, entonces todos los pivotes son mayores que 0.

### Ejemplo Básico

In [29]:
# =====================================================
# COMPLETAR ===========================================
# -
# AYUDA:
# Estructura esperada
#matrix, pivots = sympy.Matrix(A).rref()
A_sim = obtener_forma_simetrica(A) 

n , _ = A_sim.shape

for i in range(n):
    aii = A_sim[i,i] 
    for j in range(i + 1,n):
        aij = A_sim[i,j]
        for k in range(n):
            A_sim[j,k] = 1/aii*(-aij)* A_sim[i,k] +   A_sim[j,k]

piv = [A_sim[i,i] for i in range(n)]
print(piv)
# =====================================================

# Identifica si es positiva definida
if piv[0] > 0 and piv[1] > 0 and piv[2] > 0 and piv[3] > 0:
    print('Todos los pivotes de la forma escalonada son mayores que 0 i.e la matriz es positiva definida')
else: 
    print('Error, la matrix no se identifica como positiva definida')

[1.0, 3.0, 1.6666666666666667, 1.6]
Todos los pivotes de la forma escalonada son mayores que 0 i.e la matriz es positiva definida


### Método General

Utilice la libreria numpy para realizar una función que determine si una matriz es positiva definida . Encuentre el valor de los pivotes cuando esta matriz es reducida en forma escalonada y a partir de esto tome su decisión.

In [30]:
def positiva_definida_pivots(A):
    """ 
    Verifica si una matriz es positva definida
    utiliza el método de pivotes
    ___________________________________
    Entrada:
    A:   [2D-array] Matriz a revisar
    ___________________________________
    Salida:
    Ar : [2D-array] Matriz en forma escalonada
    out: [boolean]  Respuesta de verificación. True: Es p.d. False: no es p.d.
    """
    # =====================================================
    # COMPLETAR ===========================================
    # -
    # AYUDA:
    # Estructura esperada
    A_sim = A
    n , _ = A_sim.shape
    for i in range(n):
        aii = A_sim[i,i] 
        for j in range(i + 1,n):
            aij = A_sim[i,j]
            for k in range(n):
                A_sim[j,k] = 1/aii*(-aij)* A_sim[i,k] +   A_sim[j,k]

 
    Ar = A_sim
    piv = [A_sim[i,i] for i in range(n)]
    
    for x in piv:
        if x < 0:
            out = False
            break 
        else:
            out = True
    # =====================================================
    
    return out, Ar

### Prueba

In [31]:
Alist = mutils.generar_matrices_balanceadas(dim=[2,3], n=2, rnd=1, as_int=True)

mutils.mostrar_resultados(Alist, positiva_definida_pivots)


-23	378
0	6249

La matriz NO ES positiva definida
Los valores obtenidos para esta prueba son:
[[ -23  378]
 [   0 6249]]
__________________________________

-406	-74	-39
0	-103	-560
0	0	2876

La matriz NO ES positiva definida
Los valores obtenidos para esta prueba son:
[[-406  -74  -39]
 [   0 -103 -560]
 [   0    0 2876]]
__________________________________

2255	-478
0	394

La matriz ES positiva definida
Los valores obtenidos para esta prueba son:
[[2255 -478]
 [   0  394]]
__________________________________

-408	229	-167
0	-339	-481
0	0	39

La matriz NO ES positiva definida
Los valores obtenidos para esta prueba son:
[[-408  229 -167]
 [   0 -339 -481]
 [   0    0   39]]
__________________________________

1913	610
0	131

La matriz ES positiva definida
Los valores obtenidos para esta prueba son:
[[1913  610]
 [   0  131]]
__________________________________

791	677	-39
0	2740	44
0	0	297

La matriz ES positiva definida
Los valores obtenidos para esta prueba son:
[[ 791  677  -39]
 [

In [32]:
# ============================================================
# PRUEBAS AVANZADAS ==========================================
# ============================================================

mutils.correr_prueba_positiva_definida_pivots(positiva_definida_pivots)


__________________________________
Verificando errores...




Sin Errores
__________________________________


## Datos

A continuación se presenta la [base de datos de iris](https://scikit-learn.org/stable/datasets/toy_dataset.html#iris-dataset), la cual se utiliza de manera estándar para probar algoritmos de clasificación. Esta base de datos consiste en 150 instancias, cada una con 4 propiedades númericas y una propiedad cualitativa. Esta es una bse de datos libre que se encuentra dentro de las bases de datos disponibles en la libreria sklearn.

In [33]:
# Base de datos IRIS - Cargada de internet
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
data = pd.read_csv(url, names=['sepal length','sepal width','petal length','petal width','target'])
data[:5]

sepal length  sepal width  petal length  petal width       target
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [34]:
# Base de datos IRIS - Cargada de sklearn
iris_dataset = datasets.load_iris()
print(iris_dataset.keys())
# Predictores
data = pd.DataFrame(iris_dataset['data'], columns=iris_dataset['feature_names'])
# Objetivo
data['target'] = [iris_dataset['target_names'][i] for i in iris_dataset['target']]
data.head()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

### Matrices covarianza

Utilice funciones internas de la libreria numpy para encontrar la matriz de covarianza entre las variables de la tabla. Observe que dado que se tienen 4 variables númericas, se pueden obtener matrices de covarianza por cada subtabla con 4 o mas instancias y que dependiendo de los datos que se utilicen la matriz de covarianza cambiará. Complete la siguiente función para obtener todas las matrices de correlación para submuestras de 4 a 10 elementos de los datos. 

In [35]:
def obtener_matrices_covarianza(data):
    """ 
    Obtiene matrices de covarianza para submuestras de 4 a 10 elementos.
    ___________________________________
    Entrada:
    data:   [pd.DataFrame] Base de datos a revisar
    ___________________________________
    Salida:
    corr_matrices : [list] lista de matrices de correlación de las distintas submuestras
    """
    cov_matrices = []
    # Itera sobre diferentes subtablas
    for i in range(4,11):
        for j in range(len(data) - i):
            # Selecciona datos
            df = data[j:j+i]
            df = df.drop(['target'], axis = 1)
            df_array = df.to_numpy()
            # =====================================================
            # COMPLETAR ===========================================
            cov = np.cov(df_array)
            
            # =====================================================
            
            cov_matrices.append(cov)
            
    return cov_matrices

In [37]:
cov_matrices = obtener_matrices_covarianza(data)

### Resultados

Ahora pruebe cada una de sus funciones sobre este conjunto de matrices. Verifique que si la matriz no se identifica como positiva definida entonces se tiene el caso que uno de los valores que se encontraron para determinar si la matriz es p.d. es igual a 0.

In [38]:
def resultados_covarianza(fun, cov_matrices):
    """ 
    Muestra los resultados de aplicar una función para detectar si una matriz es positiva definida
    sobre las diferentes matrices de covarianza encontradas
    ___________________________________
    Entrada:
    fun:   [function] función a evaluar
    corr_matrices : [list] lista de matrices de correlación de las distintas submuestras
    """
    pd_list = []
    vals0 = []
    
    for A in cov_matrices:
        out, vals = fun(A)
        print(out)
        print(vals)
        
        # Selecciona los valores relevantes para la función de pivotes
        if fun == positiva_definida_pivots:
            vals = np.array(vals)
            vals = [vals[i,i] for i in range(vals.shape[0])]
            
        # =====================================================
        # COMPLETAR ===========================================
        # Agrega un indicador si alguno de los valores es igual a 0
        # Recuerde que debido a las aproximaciones que el computador hace constantemente
        # es posible que el computador apróxime un 0 con un valor muy pequeño.
        # Pruebe utilizando 10^-5 como tolerancia.
        vals0.append(False)
        # =====================================================
        pd_list.append(out)
        
    return pd_list, vals0

### Prueba

Finalmente verificamos que para todas las matrices de correlación encontradas se tiene que son positivas definidas o que alguno de sus valores es igual a 0 por lo que se espera que sea a lo sumo positiva semi-definida. Utilizamos la siguiente funci´pon para realiar dicha prueba:

In [39]:
def correr_prueba_datos(resultados_covarianza, test_fun, cov_matrices):
    """ Modulo de pruebas funciones resultados_covarianza, cov_matrices 
    y para las 3 funciones que identifican si una matriz es positiva definida o no."""
    print(mutils.PLINE, 'Verificando errores...\n\n', sep='\n')

    pd_list, vals0 = resultados_covarianza(test_fun, cov_matrices)

    for i, (pd_val, vals0_val) in enumerate(zip(pd_list, vals0)):
        if not(pd_val or vals0_val):
            print('Se encontro una matriz que no es ni positiva definida ni tiene valores en 0:')
            print(f"    Matriz {i} : \n {cov_matrices[i]}\n")
            assert False  

    print('\n\nSin Errores', mutils.PLINE, sep='\n')

In [40]:
# ============================================================
# PRUEBAS AVANZADAS ==========================================
# ============================================================

print('Identificación con vectores propios:\n')

correr_prueba_datos(resultados_covarianza, positiva_definida_vprop, cov_matrices)

Identificación con vectores propios:

__________________________________
Verificando errores...


True
[1.65178969e+01 2.11439743e-02 1.45682086e-15 6.79244079e-03]
True
[1.64041249e+01 3.55014282e-02 6.20702971e-03 4.83276450e-16]
True
[1.72557339e+01 1.47880828e-02 2.81138645e-03 2.32293971e-16]
True
[1.70140097e+01 1.82073448e-02 9.22373185e-17 2.82996589e-04]
True
[1.78146020e+01 1.02102516e-02 1.87789944e-04 1.30312298e-15]
True
[1.64766585e+01 2.07628251e-02 5.38925636e-16 7.86802425e-05]
True
[1.57687069e+01 3.20494438e-02 7.69683804e-05 8.66515124e-17]
False
[ 1.73610533e+01  1.69027609e-02  3.77249290e-04 -5.78711405e-16]
True
[1.69711883e+01 1.73011440e-02 1.17040327e-15 7.34393503e-03]
True
[1.77711579e+01 2.32895980e-02 3.23735992e-18 8.05246113e-03]
True
[1.70400874e+01 2.16771647e-02 1.15359111e-16 9.90208229e-03]
False
[ 1.82577209e+01  5.82946532e-02  1.56511627e-02 -3.09437862e-16]
True
[2.02583537e+01 8.07314065e-02 1.36856704e-16 1.25815860e-02]
True
[2.15161943e+01 

  1.53588364e-15 -1.40071721e-15 -8.57304025e-16]
False
[ 2.97844565e+01+0.00000000e+00j  2.00771886e-01+0.00000000e+00j
  4.56049231e-02+0.00000000e+00j -1.73201928e-15+1.29519725e-15j
 -1.73201928e-15-1.29519725e-15j  3.87140610e-16+0.00000000e+00j
  9.30288181e-16+0.00000000e+00j]
False
[ 2.96418202e+01  1.81373468e-01  4.51397094e-02  2.13274496e-15
 -5.58708569e-16  6.85980559e-16  1.55675772e-16]
False
[ 3.00209237e+01  1.65028981e-01  4.98806256e-02 -1.26990134e-15
 -3.30887551e-16  9.06619323e-16  1.16572480e-15]
False
[ 2.95931335e+01+0.00000000e+00j  5.61111763e-02+0.00000000e+00j
  3.24220373e-02+0.00000000e+00j -4.31062585e-16+0.00000000e+00j
  5.78815587e-16+1.65510604e-16j  5.78815587e-16-1.65510604e-16j
  9.37002725e-16+0.00000000e+00j]
False
[ 2.95225001e+01  5.26963946e-02  3.23034809e-02 -6.45892699e-16
  1.03243560e-15  8.61681708e-16  1.19796314e-16]
False
[ 3.04703726e+01+0.00000000e+00j  3.56476965e-02+0.00000000e+00j
  2.81464030e-02+0.00000000e+00j -5.98766766e-

False
[ 4.88103350e+01+0.00000000e+00j  2.07761792e-01+0.00000000e+00j
  1.17736554e-01+0.00000000e+00j  2.70594952e-15+0.00000000e+00j
 -2.13907721e-15+0.00000000e+00j  9.93076867e-16+0.00000000e+00j
 -1.08885241e-15+0.00000000e+00j -1.25031940e-16+3.49621919e-17j
 -1.25031940e-16-3.49621919e-17j]
False
[ 4.84958553e+01+0.0000000e+00j  1.83833484e-01+0.0000000e+00j
  1.21977845e-01+0.0000000e+00j  2.11844018e-15+0.0000000e+00j
 -1.40790696e-15+2.9553103e-16j -1.40790696e-15-2.9553103e-16j
  6.70826699e-16+0.0000000e+00j  3.09845392e-16+0.0000000e+00j
 -5.02332276e-16+0.0000000e+00j]
False
[ 4.86134986e+01  1.80393624e-01  1.18607772e-01  5.36433938e-15
 -2.41888354e-15 -1.09008166e-15  2.13479926e-16 -7.70317280e-17
 -2.01565405e-16]
False
[ 4.55375104e+01+0.00000000e+00j  1.91986503e-01+0.00000000e+00j
  1.29669803e-01+0.00000000e+00j -3.93578153e-15+0.00000000e+00j
 -1.21079889e-16+9.45163916e-16j -1.21079889e-16-9.45163916e-16j
  5.09786940e-16+0.00000000e+00j -7.75547565e-16+0.000

AssertionError: 

In [41]:
# ============================================================
# PRUEBAS AVANZADAS ==========================================
# ============================================================

print('Identificación con determinantes:\n')

correr_prueba_datos(resultados_covarianza, positiva_definida_det, cov_matrices)

Identificación con determinantes:

__________________________________
Verificando errores...


True
[4.75, 0.157, 0.0, 0.0]
True
[4.149, 0.112, 0.001, 0.0]
True
[3.99, 0.049, 0.0, 0.0]
True
[3.657, 0.111, 0.0, -0.0]
True
[4.65, 0.005, 0.0, 0.0]
True
[4.977, 0.01, 0.0, 0.0]
True
[3.749, 0.068, 0.0, 0.0]
True
[4.449, 0.018, 0.0, -0.0]
True
[3.322, 0.007, 0.0, -0.0]
True
[4.28, 0.141, 0.002, -0.0]
True
[5.327, 0.07, 0.002, 0.0]
True
[4.067, 0.118, 0.002, -0.0]
True
[4.129, 0.145, 0.003, 0.0]
True
[3.549, 0.08, 0.003, 0.0]
True
[6.587, 0.233, 0.0, 0.0]
True
[6.087, 0.101, 0.002, 0.0]
True
[5.323, 0.111, 0.0, -0.0]
True
[4.596, 0.045, 0.001, -0.0]
True
[5.616, 0.212, 0.001, -0.0]
True
[4.722, 0.464, 0.001, 0.0]
True
[5.009, 0.344, 0.0, 0.0]
True
[4.496, 0.183, 0.001, -0.0]
True
[4.357, 0.735, 0.049, 0.0]
True
[3.983, 0.27, 0.003, 0.0]
True
[3.909, 0.285, 0.007, 0.0]
True
[4.197, 0.148, 0.0, -0.0]
True
[4.08, 0.002, 0.0, -0.0]
True
[4.847, 0.016, 0.0, 0.0]
True
[4.863, 0.103, 0.001, -0.0]
Tr

True
[3.567, 0.009, 0.0, -0.0, -0.0, -0.0, 0.0, 0.0, 0.0]
True
[3.67, 0.009, 0.0, 0.0, -0.0, 0.0, 0.0, -0.0, -0.0]
True
[3.78, 1.041, 0.039, -0.0, 0.0, 0.0, 0.0, -0.0, 0.0]
True
[4.19, 0.278, 0.011, -0.0, -0.0, 0.0, 0.0, 0.0, 0.0]
True
[2.94, 0.179, 0.011, 0.0, -0.0, 0.0, -0.0, -0.0, -0.0]
True
[3.436, 0.213, 0.003, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
True
[4.947, 0.342, 0.002, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0]
True
[4.969, 0.703, 0.0, -0.0, 0.0, 0.0, -0.0, -0.0, -0.0]
True
[3.287, 0.162, 0.006, -0.0, 0.0, 0.0, 0.0, -0.0, 0.0]
True
[3.322, 0.138, 0.001, -0.0, -0.0, 0.0, -0.0, 0.0, 0.0]
True
[3.629, 0.084, 0.001, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0]
True
[4.109, 0.101, 0.001, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0]
True
[3.867, 0.029, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
True
[2.847, 0.126, 0.003, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0]
True
[3.457, 0.096, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0]
True
[3.623, 0.021, 0.0, 0.0, -0.0, -0.0, 0.0, -0.0, 0.0]
True
[3.509, 0.051, 0.003, -0.0, -0.0, -0.0, 0.0, 0.0, -0.0]
True
[4.

In [42]:
# ============================================================
# PRUEBAS AVANZADAS ==========================================
# ============================================================

print('Identificación con pivotes:\n')

correr_prueba_datos(resultados_covarianza, positiva_definida_pivots, cov_matrices)

Identificación con pivotes:

__________________________________
Verificando errores...


True
[[ 4.75000000e+00  4.42166667e+00  4.35333333e+00  4.16000000e+00]
 [ 0.00000000e+00  3.31380117e-02  2.58128655e-03  1.25508772e-02]
 [ 0.00000000e+00  0.00000000e+00  7.11773080e-06 -2.47826445e-04]
 [ 0.00000000e+00  1.73472348e-18  2.71050543e-19  1.91320744e-12]]
True
[[ 4.14916667e+00  4.05500000e+00  3.88500000e+00  4.35833333e+00]
 [ 0.00000000e+00  2.70295240e-02  1.65046529e-02  4.39137712e-02]
 [-4.44089210e-16  0.00000000e+00  8.93652681e-03  2.33599181e-03]
 [-7.72094310e-16  0.00000000e+00  0.00000000e+00  1.77635684e-15]]
True
[[ 3.99000000e+00  3.81333333e+00  4.30333333e+00  4.45333333e+00]
 [ 0.00000000e+00  1.21776664e-02 -2.79309385e-03  5.15176831e-04]
 [ 0.00000000e+00 -8.87744739e-16  8.08674442e-03  7.06608735e-03]
 [ 0.00000000e+00 -1.12479133e-16  0.00000000e+00  5.75060832e-16]]
True
[[ 3.65666667e+00  4.11000000e+00  4.25666667e+00  3.68833333e+00]
 [ 0.00000000e+00

   6.93889390e-18  1.64321553e-15]]
False
[[ 4.22250000e+00  3.57500000e+00  4.53666667e+00  3.66500000e+00
   4.18000000e+00  4.36333333e+00]
 [-4.44089210e-16  1.49875666e-01  1.29009276e-01 -2.98993487e-03
   6.43161634e-02 -2.42372212e-02]
 [-5.05917384e-16  0.00000000e+00  8.07705588e-03 -8.44666544e-03
  -3.03297253e-03  3.28843796e-02]
 [-5.37927710e-16  0.00000000e+00  0.00000000e+00 -5.46437895e-16
  -8.50014503e-16  3.63598041e-15]
 [ 8.37374136e-16  0.00000000e+00  8.88178420e-16  0.00000000e+00
   7.67133270e-16 -2.72949102e-15]
 [ 1.38799867e-15  0.00000000e+00  4.04835294e-15  0.00000000e+00
  -7.88860905e-31  1.46485929e-14]]
False
[[ 3.17666667e+00  3.97000000e+00  3.10000000e+00  3.60333333e+00
   3.67000000e+00  3.39833333e+00]
 [-4.44089210e-16  3.18747814e-02  5.24798881e-02  4.01119272e-02
   1.13462749e-01  4.63081497e-02]
 [ 7.31165862e-16  4.44089210e-16  7.84114269e-02  4.75887926e-02
  -1.49032518e-02  2.24395552e-02]
 [ 1.15098715e-16 -2.69522825e-16 -6.93889

False
[[ 4.97666667e+00  4.31833333e+00  4.70166667e+00  4.05500000e+00
   4.59333333e+00  5.14666667e+00  4.49333333e+00  4.51166667e+00]
 [ 0.00000000e+00  2.07970529e-03 -3.87809779e-03 -6.08841259e-03
  -9.04219692e-03 -2.51172137e-03 -2.27059612e-03 -9.01205626e-03]
 [ 0.00000000e+00  4.33680869e-19  7.24637681e-05  2.17391304e-04
   2.89855072e-04 -2.89855072e-04  7.24637681e-04  3.90312782e-15]
 [-8.88178420e-16 -1.30104261e-18 -2.71050543e-20  7.10878838e-15
   1.39158433e-14 -2.48688873e-14  3.90846210e-14 -5.17641485e-15]
 [ 1.73865799e-15  8.12138812e-19  5.30596310e-20  4.40728183e-16
  -2.47611445e-15  9.01602444e-15 -8.22810454e-15  2.83339970e-15]
 [ 3.22365784e-15 -8.88038014e-16  9.83782300e-20  1.60380306e-15
   0.00000000e+00  2.75359051e-14 -2.73359639e-14  1.38141448e-14]
 [ 2.30597444e-15 -8.81472186e-16 -3.80474621e-20  1.27622147e-16
  -8.88612101e-16  4.33680869e-19 -3.60094846e-15  8.46800389e-16]
 [ 2.67824842e-16  2.38203327e-16 -1.73227734e-20  1.70361529e-

  -5.28238741e-16]]
False
[[ 4.14916667e+00  4.05500000e+00  3.88500000e+00  4.35833333e+00
   4.51500000e+00  3.90750000e+00  4.28416667e+00  3.70750000e+00
   4.21000000e+00]
 [ 0.00000000e+00  2.70295240e-02  1.65046529e-02  4.39137712e-02
   4.08027047e-02  4.28486309e-02  2.47305349e-02  1.16429002e-02
   5.54729865e-03]
 [-4.44089210e-16  0.00000000e+00  8.93652681e-03  2.33599181e-03
   4.21021780e-03  3.44966232e-03  5.16091214e-03  6.43755882e-03
   7.98583247e-03]
 [-7.72094310e-16  0.00000000e+00  0.00000000e+00  1.77635684e-15
   2.46330734e-15  4.23164108e-16  1.68528386e-15  1.77592316e-16
   4.31512465e-16]
 [ 1.27989902e-15  0.00000000e+00  0.00000000e+00 -2.16840434e-19
   7.60838875e-17  2.17270177e-15 -5.19891882e-16 -4.55304773e-16
  -4.42694994e-16]
 [-3.61942871e-14  4.44089210e-16  3.03576608e-18  8.94153818e-16
   1.38777878e-17 -5.98860026e-14  1.61640184e-14  1.27176840e-14
   1.26327708e-14]
 [-9.22787818e-16  1.19865509e-16  8.19393126e-19  2.39862155e-16
  

[[ 3.65666667e+00  4.11000000e+00  4.25666667e+00  3.68833333e+00
   4.03166667e+00  3.48500000e+00  3.95333333e+00  4.40666667e+00
   3.85333333e+00  3.88166667e+00]
 [ 0.00000000e+00  3.04649043e-02  2.56153145e-02  2.94074749e-02
   1.01762382e-02 -2.05104831e-03 -1.01124278e-02  2.03524765e-02
   8.95168642e-03 -7.89425706e-03]
 [ 0.00000000e+00  0.00000000e+00  1.19688809e-05  7.77977259e-05
  -8.77717933e-05 -1.07719928e-04 -1.75543587e-04 -1.75543587e-04
   2.03470975e-04 -2.81268701e-04]
 [-4.44089210e-16  3.46944695e-18 -8.88178420e-16  1.59976199e-14
  -2.82999535e-14 -3.31146785e-14 -5.39284329e-14 -5.26169820e-14
   6.00062534e-14 -8.62318029e-14]
 [-1.67377678e-15  7.87221069e-18 -2.45762687e-15 -3.15544362e-30
  -5.08022701e-15 -5.22715885e-15 -9.59423892e-15 -4.58219476e-15
   5.96901125e-15 -1.17552194e-14]
 [ 3.58843336e-16 -1.35190438e-18 -1.98195590e-16 -4.33680869e-19
   1.08420217e-19 -1.14709259e-15  4.71341155e-17 -1.03213980e-15
   1.14446592e-15 -1.68399818e-15

   8.88178420e-16  3.53256915e-15]]
False
[[ 7.95333333e+00  5.71333333e+00  5.92666667e+00  6.94666667e+00
   5.48666667e+00  5.32000000e+00  5.90666667e+00  7.14000000e+00
   7.37666667e+00  7.29000000e+00]
 [-8.88178420e-16  9.82865326e-02  6.42036882e-02  7.81461302e-02
   1.08614138e-01  1.00006985e-01  1.27374965e-02  9.75970942e-02
   5.25859179e-02  1.29010198e-01]
 [-3.07993843e-16  0.00000000e+00  3.16254818e-02  3.57673748e-02
   7.16121681e-03  2.69803682e-02  5.14833425e-03  2.89932508e-02
  -1.29676088e-03  5.16962435e-02]
 [ 1.05450804e-15  8.88178420e-16 -6.93889390e-18 -5.96744876e-16
   3.46944695e-17 -3.74700271e-16 -1.75207071e-16 -1.69309011e-15
  -2.43533492e-15 -2.08166817e-17]
 [ 2.24376860e-16  5.16382802e-17 -4.03424064e-19  1.73472348e-18
  -1.24741746e-15  6.92880830e-17  1.20411998e-15 -6.21454600e-16
  -1.14474730e-15 -1.24375639e-16]
 [-3.71366739e-16 -5.54825166e-16 -4.39754638e-16  3.56580256e-18
  -1.38777878e-17  8.46278753e-16  1.31747754e-15  3.3816

AssertionError: 